apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: local-kind-cluster
nodes:
- extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: 0.0.0.0
  - containerPort: 443
    hostPort: 443
    listenAddress: 0.0.0.0
  role: control-plane
- role: worker
- role: worker
